# Generated by Django 3.1.7 on 2021-04-04 10:18

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('symbol', models.CharField(blank=True, max_length=255, unique=True, verbose_name='symbol')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('buy_price', models.CharField(blank=True, max_length=255, null=True, verbose_name='buy_price')),
                ('target_price', models.CharField(blank=True, max_length=255, null=True, verbose_name='target_price')),
                ('support_price', models.CharField(blank=True, max_length=255, null=True, verbose_name='support_price')),
                ('percent_target', models.CharField(blank=True, max_length=255, null=True, verbose_name='percent_target')),
                ('percent_support', models.CharField(blank=True, max_length=255, null=True, verbose_name='percent_support')),
                ('profit_loss_ratio', models.CharField(blank=True, max_length=255, null=True, verbose_name='profit_loss_ratio')),
                ('is_high_liquidity', models.BooleanField(default=False, verbose_name='is_high_liquidity')),
                ('is_good_character', models.BooleanField(default=False, verbose_name='is_good_character')),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'stocks',
                'ordering': ('-id',),
            },
        ),
    ]
