# Generated by Django 3.1.7 on 2021-04-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='est_buy_tich_san',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='est_buy_tich_san'),
        ),
        migrations.AddField(
            model_name='stock',
            name='est_sell_tich_san',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='est_sell_tich_san'),
        ),
    ]
