# Generated by Django 3.1.7 on 2021-05-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210414_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_blacklist',
            field=models.BooleanField(default=False, verbose_name='is_blacklist'),
        ),
    ]
