# Generated by Django 3.1.7 on 2021-05-22 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stock_is_blacklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='is_good_character',
        ),
    ]
